### PR TITLE
feat: Added useMediaSizes to docs

### PR DESCRIPTION
**Pull request by epoll31**
feat: #38 

Added `useMediaSizes` to docs with a simple example.

### CODE REVIEW

**Comment by Ansub** [comment]
@epoll31, could you also add your name to the Credits section in `app/docs/page.mdx`?

**Comment by epoll31** [comment]
@Ansub Do you want that in this same PR, or in a new one?

**Comment by Ansub** [comment]
you can do it in the same PR as this is related to what you have built.

**Comment by epoll31** [comment]
@Ansub I went ahead and added the credit to the docs and I added the rest of the credits to the README.md (#45).
I also noticed a spelling mistake in the docs that I fixed. (Sponsers -> Sponsors).

**Comment by Ansub** [comment]
awesome, can you rebase main and resolve conflicts?

**Comment by epoll31** [comment]
I just fixed the conflicts in the page and added the new credit to the README

**Pull request merged**
