### PR TITLE
fix: migrate from shiki v0.14 to v1.3.0

### PR DESCRIPTION
**Pull request by epoll31**
fix: #101  migrated from shiki v0.14 to v1.3.0

updates:
- organized all components related to demoing code into a folder
```
./src/components/code
├── Code.tsx
├── CodeGroup.tsx
├── CodeGroupFromFile.tsx
├── ComponentPreview.tsx
└── PreviewCodeGroup.tsx
```
- enables support of demoing code using backticks (inline and multiline), `RawCode` (equivalent of backticks), `Code`, `CodeGroup`, `CodeGroupFromFile`, `PreviewCodeGroup`, and `ComponentPreview`
- still uses shiki css-variables defined in `src/styles/tailwind.css`
- syntax highlighting is performs in `src/lib/codeToHtml.ts`
- removed all unnecessary and/or old components related to demoing code

### CODE REVIEW

**Comment by Ansub** [comment]
build faliure: 
CleanShot 2024-04-29 at 23 30 38@2x


did you try `npm run build` locally?

**Comment by epoll31** [comment]
There was an issue in the demo page import that I didn't fix, just fixed this and it built

**Comment by Ansub** [comment]
Still failing: 
CleanShot 2024-04-29 at 23 41 24@2x

**Comment by epoll31** [comment]
I removed the ComponentPreview from the demo page. The build should work now.

**Comment by Ansub** [comment]
Change you made in `pricing/page.mdx` is breaking the UI. do check the previews of files you are making changes of :) 
 
CleanShot 2024-04-30 at 10 59 16@2x

**Comment by Ansub** [comment]
CleanShot 2024-04-30 at 11 01 17@2x

**Comment by Ansub** [comment]
remove the unused code in `src/mdx/rehype.mjs`

CleanShot 2024-04-30 at 11 05 33@2x

**Comment by Ansub** [comment]
revert this copy change and please avoid making any change which is unrelated the PR title

CleanShot 2024-04-30 at 11 06 54@2x

**Comment by Ansub** [comment]
there is no need to add this in showcase `src/showcase/hooks/useMediaSizes.tsx`

**Comment by Ansub** [comment]
remove .vscode for now, no usage atm
CleanShot 2024-04-30 at 11 14 14@2x

**Comment by epoll31** [comment]
> Change you made in `pricing/page.mdx` is breaking the UI. do check the previews of files you are making changes of :)
> 
> CleanShot 2024-04-30 at 10 59 16@2x

Fixed! I did not realize how broken this looked. Thanks for the comment!

> will do this in next iteration, current one looks better than this one
> 
> CleanShot 2024-04-30 at 11 01 17@2x

Fixed! I am not sure why this wasn't fixed. I guess I didn't stage a change properly in git or something.

> remove the unused code in `src/mdx/rehype.mjs`
> 
> CleanShot 2024-04-30 at 11 05 33@2x

Fixed! Residual comments removed.

> revert this copy change and please avoid making any change which is unrelated the PR title
> 
> CleanShot 2024-04-30 at 11 06 54@2x

Fixed! This was my attempt to make the cards align better, but clearly was not the correct solution.

> there is no need to add this in showcase `src/showcase/hooks/useMediaSizes.tsx`

Fixed! Leftover file from testing CodeGroupFromFile. I had meant to remove this. Good catch!

> remove .vscode for now, no usage atm CleanShot 2024-04-30 at 11 14 14@2x

Fixed! I am not sure why this was added. I can add it to our `.gitignore` in another pr.

**Pull request merged**
