### PR TITLE
Feat: Added Four Column Responsive Footer

### LINKED ISSUE #197: [FEATURE]: Add a 4 column responsive Footer
### Feature Description 📝

Will have 4 columns and a desc and will be responsive as well. The footer will actually be a professional one

### Screenshots 📸

image
image

### PR DESCRIPTION
**Pull request by subhadeeproy3902**
Added a simple four column responsive footer that looks and is professinally used

## Related Issue

Please link to the issue that this pull request addresses or resolves.

Fixes #197 

## Screenshots

image
image

## Checklist

Please check the boxes that apply:

- [x] I have rebased my branch on top of the latest `main` branch.
- [x] I have tested the changes locally
- [x] I ran `npm run build` and build is successful
- [x] I have added necessary documentation (if applicable)
- [x] I have updated the credits.md file (if applicable)

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
@Ansub Please check and review it. Thanks... its 💯

**Comment by subhadeeproy3902** [comment]
@Ansub is it alright ?...

**Comment by Ansub** [comment]
Hey @subhadeeproy3902 i am a little busy this week that's why not getting time to review the changes, i will lyk once i wil be reviewing this PR :) 

in a meantime you can ask the contributors on discord how they are liking the change they can provide some valuable feedbacks :)

**Comment by Ansub** [comment]
this looks quite cluttered, make it three columns instead of four and also add some socials icons icons at the bottom part where we have the copyright stuff, you can copy the logos from `Minimal Centered Footer` component. 

also please match the styling like i have of two columns footer
CleanShot 2024-05-23 at 13 05 13@2x

**Comment by subhadeeproy3902** [comment]
@Ansub i will be adding social buttons... but i have labeles issue to be four column footer... four columns are professional thats why

**Pull request closed without merging**
