### PR TITLE
Feat: Added four column footer as requested

### PR DESCRIPTION
**Pull request by subhadeeproy3902**
Added the professionally used four column footer with the reviewed changes

Fixed issue #199 

## Proposed Changes

- Add the social icons

## Screenshots

sdvdfbv

dsdfs

## Checklist

Please check the boxes that apply:

- [x] I have rebased my branch on top of the latest `main` branch.
- [x] I have tested the changes locally
- [x] I ran `npm run build` and build is successful
- [x] I have added necessary documentation (if applicable)
- [x] I have updated the credits.md file (if applicable)

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
@Ansub Please check now ... i made the changes !!

**Comment by subhadeeproy3902** [comment]
@Ansub Is there any more changes are required ??

**Comment by Ansub** [comment]
I am not seeing the changes i told in the older [PR made](https://github.com/Ansub/SyntaxUI/pull/199#issuecomment-2126606775), it looks exactly the same as the order one.

Also please try to make change in the same PR else the conversation gets lost

**Comment by subhadeeproy3902** [comment]
> ange in the same PR else the conve

@Ansub sorry for that ... but u told to add the social icons ... I added them ... but u asked me to make a 3 column one... but i would rather say in professional websites 4 column ones are preferred !.. so i didnt change that !

**Comment by Ansub** [comment]
> > ange in the same PR else the conve
> 
> @Ansub sorry for that ... but u told to add the social icons ... I added them ... but u asked me to make a 3 column one... but i would rather say in professional websites 4 column ones are preferred !.. so i didnt change that !

I actually told you to replace the last grid column with the social icons, but no worries I actually have the component pre-made i will be adding that you can see what i actually meant by that then.

also i am not planning on adding four columns footers now as the code is pretty easy for anyone to duplicate, i am looking for some unique footers which makes SyntaxUI stand out.

**Comment by subhadeeproy3902** [comment]
> > > ange in the same PR else the conve
> > 
> > 
> > @Ansub sorry for that ... but u told to add the social icons ... I added them ... but u asked me to make a 3 column one... but i would rather say in professional websites 4 column ones are preferred !.. so i didnt change that !
> 
> I actually told you to replace the last grid column with the social icons, but no worries I actually have the component pre-made i will be adding that you can see what i actually meant by that then.
> 
> also i am not planning on adding four columns footers now as the code is pretty easy for anyone to duplicate, i am looking for some unique footers which makes SyntaxUI stand out.

ok alryt. Close the PR then

**Pull request closed without merging**
