### PR TITLE
feat: New Preview Code Tab component

### PR DESCRIPTION
**Pull request by Ansub**
Demo: 

https://github.com/Ansub/SyntaxUI/assets/12985873/86adaacf-4a8c-4d65-86e2-ba7d8dd38a7b

### CODE REVIEW

**Comment by krishpatel023** [comment]
So, @Ansub  want to remove-syntax-highlighter and add shiki instead?

[refer This](https://github.com/nikolailehbrink/shiki-next)

Or else give me a stating point and will contribute directly :)

**Comment by krishpatel023** [comment]
Sure @Ansub ,
 whenever you are done create a new issue linking the component that needs to be fixed and assign it to me. I'll look into it.

**Comment by Ansub** [comment]
gotcha will be do that, you can also join the discord.

https://discord.gg/P8GXYyH3ZU

**Comment by Ansub** [comment]
also created the issue here: https://github.com/Ansub/SyntaxUI/issues/101

you can message so that i can assign this issue to you :)

**Pull request merged**
