### PR TITLE
Added Toggle section with a normal toggle switch / updated credits to reflect addition

### PR DESCRIPTION
**Pull request by epoll31**
feat: Added Toggle section with a normal Toggle switch

### CODE REVIEW

**Comment by Ansub** [comment]
please create a seperate pr for component data issue, otherwise it will have to stay if we want to make changes in toggle component. 

it's always better to divide pr on the basis of tasks

**Comment by epoll31** [comment]
Sounds good, I removed that from this PR and I will create a new PR for that issue. Let me know if you have any other comments on this code.

**Comment by epoll31** [comment]
I just pulled in the updated ComponentCards id numbering into this PR and updated the new toggle id number.

**Comment by Ansub** [comment]
just reviewed the PR here are two improvements: 

1. can we remove the full toggle, it doesn't matches with normal toggle.
2. instead of adding in ui, add toggle in `components/PreviewCode` folder

**Pull request merged**
