### PR TITLE
fix: dynamic sitemap

### LINKED ISSUE #167: [FEATURE]: Make Sitemap dynamic
### Feature Description 📝

sitemap should be made so that we don't have to add every link inside sitemap for google to index, we can follow this [guide](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap#generating-a-sitemap-using-code-js-ts) by Next.js for doing it.

### PR DESCRIPTION
**Pull request by epoll31**
## Description

I added a file that dynamically generates the sitemap using Next.JS sitemap functionality.

## Related Issue

Fixes #167 

## Proposed Changes

- replaced static `src/app/sitemap.xml` with dynamic `src/app/sitemap.ts`
  - uses `fs` and `path` to recursively search through `src/app` and locate all directories with a `page.tsx` or a `page.mdx`

## Checklist

Please check the boxes that apply:

- [x] I have tested the changes locally
- [x] I ran `npm run build` and build is successful
- [x] I have added necessary documentation (if applicable)
- [x] I have updated the credits.md file (if applicable)

## Additional Context

Running `npm run build` will generate a sitemap in `.next/server/app/sitemap.xml.body`

### CODE REVIEW

**Comment by shrix1** [comment]
can we have a exclude array of strings. so its easily to remove certain route in future

**Comment by shrix1** [comment]
I think `changeFrequency: "monthly" ` is important in sitemap

**Comment by Ansub** [comment]
let's add: 

```
<changefreq>daily</changefreq>
<priority>1</priority>
```

**Comment by epoll31** [comment]
done

**Review by Ansub — APPROVED** [review]

**Pull request merged**
