### PR TITLE
feat: added greeting workflow 🤖 

### PR DESCRIPTION
**Pull request by dakshsinghrathore**
This PR resolves the issue mentioned in #89 , kindly review the PR, and merge it whenever you get chance.

### CODE REVIEW

**Comment by Ansub** [comment]
instead of saying `we will review`, can we mention `@Ansub` instead?

**Comment by dakshsinghrathore** [comment]
Will try to implement it by tonight @Ansub

**Comment by Ansub** [comment]
> Authorization

also can you add a copy to join discord if they haven't already?

this is the discord link: https://discord.com/invite/P8GXYyH3ZU

**Comment by dakshsinghrathore** [comment]
Sure @Ansub

**Comment by dakshsinghrathore** [comment]
Hey @Ansub , just ran into a problem, actually the target repo `EddieHubCommunity/gh-action-community/src/welcome@main` is using deprecated node version, implying am unable to implement automated greetings feat.

Screenshot from 2024-04-26 23-29-13
hence planning to create my own [Javascript Action ](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action), and then integrate it inside greetings.yml file
Will close this PR and create a fresh one once I am done creating the action.

**Pull request closed without merging**
